# Generated by Django 5.1.3 on 2024-11-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoomzoombotbot_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
