# Generated by Django 5.1.3 on 2024-11-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoomzoombotbot_app', '0003_rename_answers_animal_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AlterField(
            model_name='animal',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='questions', to='zoomzoombotbot_app.answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='zoomzoombotbot_app.testresult'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='test_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zoomzoombotbot_app.testresult'),
        ),
    ]
