# Generated by Django 5.1.3 on 2024-11-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoomzoombotbot_app', '0007_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='animal',
        ),
    ]
