# Generated by Django 5.1.3 on 2024-11-23 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoomzoombotbot_app', '0008_remove_answer_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='zoomzoombotbot_app.animal'),
        ),
    ]
